# Doc: http://manuel.manuelles.nl/blog/2012/06/22/integrate-travis-ci-into-grunt/

sudo: false

language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

script: npm run check && npm run build

notifications:
  email:
    recipients:
      - vyacheslav.dobrenko@wildix.com
    
group: stable,
dist: precise,
os: linux